apiVersion: v1
kind: Namespace
metadata:
  name: sso
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.10.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: 2.23.0
    app.kubernetes.io/managed-by: Helm
  name: dex
  namespace: sso
stringData:
  config.yaml: |
    issuer: https://login.sso.tanzu.world
    frontend:
      theme: tkg
    web:
      http: 0.0.0.0:5556
    expiry:
      signingKeys: "10m"
      idTokens: "5m"
    logger:
      level: "debug"
      format: "json"
    oauth2:
      skipApprovalScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: dex
spec:
  virtualhost:
    fqdn: login.sso.tanzu.world
    tls:
      secretName: sso/sso.tanzu.world
  routes:
    - services:
        - name: dex-dex
          port: 9000
