#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"envoy"}})
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #@overlay/match missing_ok=True
    external-dns.alpha.kubernetes.io/hostname: #@ "*.apps.{},*.default.{},*.sso.{},*.monitoring.{}".format(data.values.domain, data.values.domain, data.values.domain, data.values.domain)


#@overlay/match by=overlay.subset({"kind":"CustomResourceDefinition"}),expects="4+"
---
#@overlay/remove
status: