---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
  - path: [spec, healthCheckNodePort]
    type: copy
    sources: [new, existing]
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: v1
          kind: Service
