#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.10.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: 2.23.0
    app.kubernetes.io/managed-by: Helm
  annotations:
    kapp.k14s.io/versioned: ""
  name: dex
  namespace: sso
stringData:
  #@yaml/text-templated-strings
  config.yaml: |
    issuer: https://login.sso.(@= data.values.domain @)
    frontend:
      theme: tkg
    web:
      http: 0.0.0.0:5556
    expiry:
      signingKeys: "10m"
      idTokens: "5m"
    logger:
      level: "debug"
      format: "json"
    oauth2:
      skipApprovalScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: (@= data.values.github_client_id @)
        clientSecret: (@= data.values.github_client_secret @)
        redirectURI: https://login.sso.(@= data.values.domain @)/callback
        orgs: 
        - name: (@= data.values.github_org @)
        - name: (@= data.values.github_org @)-Teams
          teams:
          - (@= data.values.github_team @)
    - type: saml
      id: saml
      name: SAML
      config:
        ssoURL: (@= data.values.saml_url @)
        caData: (@= data.values.saml_caData @)
        usernameAttr: name
        emailAttr: email
        groupsAttr: groups
        redirectURI: https://login.sso.(@= data.values.domain @)/callback
    staticClients:
    - id: (@= data.values.sonarqube_client_id @)
      secret: (@= data.values.sonarqube_client_secret @)
      name: 'SonarQube'
      redirectURIs:
      - 'https://sonar.apps.(@= data.values.domain @)/oauth2/callback'
    - id: (@= data.values.kuard_client_id @)
      secret: (@= data.values.kuard_client_secret @)
      name: 'Kuard'
      redirectURIs:
      - 'https://kuard.apps.(@= data.values.domain @)/oauth2/callback'
    - id: (@= data.values.grafana_client_id @)
      secret: (@= data.values.grafana_client_secret @)
      name: 'Grafana'
      redirectURIs:
      - 'https://grafana.monitoring.(@= data.values.domain @)/login/generic_oauth'