#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Namespace
metadata:
  name: sso
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: sso
spec:
  virtualhost:
    fqdn: #@ "login.sso.{}".format(data.values.domain)
    tls:
      secretName: #@ "sso/sso.{}".format(data.values.domain)
  routes:
    - services:
        - name: dex
          port: 32000
