#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

---
#@overlay/match by=overlay.subset({"metadata":{"name":"config-certmanager"}})
---
data:
  #@overlay/remove missing_ok=True
  _example:
  #@overlay/match missing_ok=True
  issuerRef: |
    kind: ClusterIssuer
    name: letsencrypt-issuer

#@overlay/match by=overlay.subset({"metadata":{"name":"config-network"}})
---
data:
  #@overlay/remove missing_ok=True
  _example:
  #@overlay/match missing_ok=True
  autoTLS: "Enabled"
  #@overlay/match missing_ok=True
  ingress.class: contour.ingress.networking.knative.dev
  #@overlay/match missing_ok=True
  httpProtocol: "Redirected"

#@overlay/match by=overlay.subset({"metadata":{"name":"config-contour"}})
---
data:
  #@overlay/remove missing_ok=True
  _example:
  #@overlay/match missing_ok=True
  visibility: |
    ExternalIP:
      class: contour
      service: contour/envoy
    ClusterLocal:
      class: contour
      service: contour/envoy

#@overlay/match by=overlay.subset({"metadata":{"name":"config-domain"}})
---
data:
  #@overlay/remove missing_ok=True
  _example:
  #@overlay/match missing_ok=True
  #@yaml/text-templated-strings
  (@= data.values.domain @): ""