#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sealed-secrets
  namespace: kapp-controller
spec:
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/sealed-secrets/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}