apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: knative
spec:
  fetch:
  - git:
      url: https://github.com/voor/cluster-api-gitops
      ref: origin/master
      subPath: workload/knative/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}