#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: knative
  namespace: kapp-controller
spec:
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/knative/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            name: #@ data.values.workload_values
  deploy:
  - kapp: {}