#@data/values
---
git_url: https://github.com/voor/cluster-api-gitops
git_branch: origin/refactor-management-cluster

contour_secretRef:
- domain-values

kuard_secretRef:
- domain-values

externaldns_secretRef:
- certmanager-values

dex_secretRef: 
- domain-values
- grafana-client-values
- github-client-values
- sonarqube-client-values

monitoring_secretRef:
- domain-values
- grafana-client-values

letsencrypt_secretRef:
- domain-values
- certmanager-values

knative_secretRef:
- domain-values

gangway_secretRef:
- domain-values
- gangway-values