fullnameOverride: cert-manager

installCRDs: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

ingressShim:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

webhook:
  deploymentAnnotations: 
    kapp.k14s.io/change-group: "change-groups.cert-manager.io/webhook"
    kapp.k14s.io/change-rule: "upsert before upserting change-groups.kapp.k14s.io/crds"