fullnameOverride: cert-manager

installCRDs: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

ingressShim:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

webhook:
  enabled: false