---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA50WZpPk2ZHL1e6WAMV3IUjd3mZYlvVLHAjO2FI8PRij/D+G/XpHWYRuBABNaFVlFhzDoshhaBvhXHToruk2sN66rpwhKb9Ou+r1SmnlKIjLnYcdNGuL4NgW31kkKOX32n5jYC1CMp9p1bb8RB0eGuk0mnKnOSwnPKQCDR5tv12BUe1fkhf9iKiQRXvHnRcFOmbDjrq2HWMb/y3gylIDtaZFu49OLJ3V6JkBtIq3ckfi2NRf6wFDzC5861uOJReTBJaGM4pOZIedkkDX3fk6QLN6fBmVd85VWGAyhSSONrjBIVld6W57vFiFep13FjKHAuDsad+QfLBp1xwIbd/QmTx1pQt829vnls9FDVoxj2yw6MMfldAmFHdaHi3mzIJkU2pXgq0uiQX/21Zal+u3vp0+0cw/zySdRf2gs2nsPXn5PFCHO9wXyl3bTG0eRUeaib7ZDnz6QwPB71iAWbjMqx/Q7yUTTjk1Lyc15fuhv+vDm7w8nc7i8RsbilYz9nVINYT8lX/1xtvGo6dmfVrW3UHzA/lQ/4lH72oqN4Zq+vI/GtUe3lNdwapKWAeDQ6EM6s+volyxBksAKbGXLgYG/z0+EyG2+rqnFBO8PTCALj9NqIe77iv31AOoEN4N4Fwo/tEPxiKUUmTxkCWn7RAOBn5ONMfcwXOfBqLkECntMYi4XOnUn++bm4ZPk6XeboAGBmq+1i4WRP+t7QvfHJUkL2K58lU3PhhLI312KoUY0unt1rJGaRe2a/
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
