apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBSgRs9drP5y/H937nQ2WCC6X1v9R+xH6yRa8AO/PdnO1DN5MIc6mQo5itQ0orXep2MwFw6Ml/ad+OmX7S20WpCvLT02Pkn/WIzCdgT4wrLZ0kjKwAcJ5vI0gB9/OR35Ulb0PE590xZurCi7ExEeCYBfrrpg1Qr2eiafyiPOijAShSu0NgloHTZ/CVh69uLZCsl6EO7kr3LPCU7xwfrDcijFo4ZMlV9gwpznVeduUR995Lc4hMuyWKjoAJowC8s7ZSQD+DHSgqSLf/dF9PEwg/R2PToqakQfwj01B6WACiFBC6p8V9W8Egqk55XCChuqTs0WuatjNV7PTO7eZWJwpEY4ayG4fTa3W7TSOYRzS2xHGsJYXMIjoAm2o731HGyPchDptxlIzCQ77fjgtqmklK8vfvvXYEFHSZkF21nfBj+uXcHpZMSq+2mO5QWWUnGSOmFKpM6UXpAaoCt5QyIJPTsY0r6P95IjACG5iJzDpmi9hXjfteFZ/B8zGFivB6wibQ6aq2gQNUSvG+1pqRoy0YLugtgSKbBPU1szmyUkJIeKcG/XUHTuCMELX+WmD4xy2cJMHti3A81Lmpc4jjxuWwBAte5kXqj37U3XR3lfc6GyvOK/wkdUbDfBftWnHNfCkQRI/nLa+re+AmhfupHzengnZLi/1GW+xriz8b3ukpluwV3y7OnhsJNfW4EJjXf3tiZTmGvIYtmi3qnEW3fFvuuJzf+UErLqYM1ksdE4BAyAwR3abclzyPm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
status: {}

