---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    email: rcvanvo@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: rcvanvo@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: default.tanzu.world
  namespace: default
spec:
  secretName: default.tanzu.world
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.default.tanzu.world'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apps.tanzu.world
  namespace: apps
spec:
  secretName: apps.tanzu.world
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.apps.tanzu.world'