apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-config
  namespace: monitoring
spec:
  encryptedData:
    grafana.ini: AgB+4zltIx65k+nL6aAiuTrYOsAD0Q5+ozHKFPpZU9RSGrgE7BH6PhOmb/My3uUq6/URcd3w/mxGf3UGbx4ZsFjwe0BDffi87W4I/ZpZtsyJET5eNC5F59A5LBAJz1k+u0Y7Wk9ZChpvbMbsIo0dhsvaaPPlDlqMV6DsIQhMiFynTc7l51JPZiUCKKQcZgD+BUSwgH2VRoqfxbYDlp0eJuz+ESoDJmVEHsqdZxPmv3kVcZkQfvLliW6iLTeHLGcnDmhfrxDUHGchVRK4eMAJWzpgGijvRdGEb8AYymmeeY7yUOwp5741WYOdumg3Xv7DfPMX9XLGvUEolPYErWFGrF0ZOp/1AgBDkabpncg9LKRP50wLbiFKnpbodt6G9VATnkYkU8GyFL+rSK0SkkduCR4p3TiwtjK5FWKVulNoEeFH35z+cx1KSvGEuV1DwF8XRQHEsK7ODrL/6Lp0/B83HTMBfZZSq3JoQA8mHZPHCSgjO3jvy5SiOgL1EgouP+oA1+UIfX9pHI8XajIzmSEPPIRttYQI8HVY5AyceU6fBs5CSWOeMR2ZvAAw/sEpKA40kwPGn7ifg0xfEjtS85ccJfx5TM0A2plqlmpgVBxXZPqCh1TND/qYJPPsQEwxzKEyWnHYj642fgp9FD2uZH49o52YBdPckaeiU4yx+uZGRZWUiLFu+gljSuOI8jnlUWajKiZiQ7RuFVA2HEwJJAUa0ABGPl3Dvw4BkL2EdHevX7Po8dupZHayQuRX5IWRiEuTzYJ/c+iYXglHAVwSwTW35BixaN8wmJiqVa5ItVEzKsYAk0jS7dJS0jDHIaZHBMIkGQn9orLVVcGEIK1kAixoZBfCszDADMQKN3gK90sL2doAUN9bnQYDPMg2CTX0HNC4VuGcT+S7FO69EXUpRyDsU7LS5/iE3J4d+OEskkTaZa4S8lxR1bOVknNGTsyBzgMwDPqYI8jFyhx0uoIABjgFMc2V/kexyAA/g1opao9I01T5n0rnd8GBC/hhpBaAFFQNTd3UNysRgBocjWtvzQvLi2Yf2UrG00MFmj1dRzGk6HfPAk2Qyo/sFLFWTOvtaijoBJXc15+s/vN79imVKy6pmoq9YA9K0luhlVMpebg8F7Y+w49f/pD4NwH/9DvGiag0NJUB9HpsK8LxlJ4Ob9Gra4xjUhk3Zo3Ar5QEfeu6W+hOxuxs97cXBXn47S5Y4/OOMzCpw5d9O00smtcVENHeZ8yGSjb8Npg4aK8cLy1FKNTM+3DPi11iVe5laApIfODLT0AS5jirAa2hWFiiYFod4Uu4wgq5ZWxIw9w248EaqlJf0W334NswnK2Rq/QgRXdmjI63PeTuOPNMZ0lfav+x3qeeh1acD52R4UbLM7wM8gW0d3i5
  template:
    metadata:
      creationTimestamp: null
      name: grafana-config
      namespace: monitoring
    type: Opaque

