apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-config
  namespace: monitoring
spec:
  encryptedData:
    grafana.ini: AgBBS2ftuEmVPvQ1JLGZuFA1sqKrm9nl/dIn3d7sDiYZc3Cv2IeZ3iPqCILIVYSD/TmaR7neTi+30wTDpGkIV0aX+n+wSF5fNcg2TXuL96e/LzoDjBAqai0sm43FTnPFzGsouY7KDH6Q2q/Y3lBHNL7TRmoqQnbe8rNMKt1ubn1p7pgtIVpa47Q0CIDqLdiGVPk1dloKg75XbMQGyCgKOptm4l5xVCHONW6+KFNT1T3W4d2aAXymrYvfpzrJATkZVR/x0Dd3PlwMxfXjLYSt5B2khyxirfDKOP7/vgrVSF6pmzSqx28DaxnOadazKbzM5r24W77i0/9bqZiYRk3tS4zC38RcrUIwaVTvqkjCyAIJQCkORt3iEVsT6tL2NASE29xg2J8tBeZhB8RS9nzbtm0PPKs+H77oBpZ8Bw3YyFJEvBV9WGhjOntaId1zIgPFRj7pG1r6n6jqfYbOetFyyPb8Pm5lAwBH5lChFGIRFvEMgpj6fT2t9y73q2U6MSq6jnr0F7dt3cKCcDcQbQ2e/g/wAChtvuNzSBWkbmG2YADqlUbwUk+F5ZdTNG0XznkV5ai3CEeCQ5hChmey4J0JE9VYQNoJINdQclq7Nv4g1Hf5o40wOjmOUdRESLq6Rr5PoeZFUZ43AAi6xpb0OmVzwKii7q7DPm7SRrvUG9ZdRKvoZ+b3aKjBLKrpwxewo7GvNUiJOj8P6Vv2Wwu4tM6UvCZ8iom1KLZei2sm0qhNkjmL6tRr0jx8Pfy8R4TzFeSgc9/7iVq13GMgouP71BgdKWRfTH+Dr8f8yhEWQW+V+7KQbnrZCHJNtYwQmpIcWZA8fN295sdbbmbGggB3VYFV3N6a5fGrObLwVysC2j/8Ayqh6adWE5r6a5fszzPYiB44oP5cFZJRdQxy2qeTDZ1Tr1P4QhF3CkZzIS2WJwNKtPGUJeLNiZMUgyhidhwhbZckeMD5ESHBN3HNI1zjqye8XUv+M+2769vXd9tjzN0RUvE3fbwQtGPr3sfkRi4MdQf0d8WMYCX74w8dFS7srbdmQZTilYoA9A2fCXjZujLNgrc+sM8BeFvEjAxCe7rnAYEsAT8FFp+7CGMrOvZtUIrPE5nF0LaAsIAWQ/io25fzyLd61elQTbGIChT0WLJeWd7zwfJNoW/sNZaQmuZK2o8ulPwjadAB1+0gC/H+KgO7UjBELZNqnM84RGbAzR0LMjGTypLs8x+jaPzzSjf6HEtDj7FXf+4fBO3QYwb8tkdOK63CHyV4lUDc5DMku9Ot0CADqVhJfiagdX0ryNVZk8nU4QsUlI5JOtRStKhhNwvXaAT5eMg6Ximn2ODZ1M08Jt6LlJ/VyD0X/VjtqCXph9EezpBioms4+nRk1RnFFRjX1w8kG3UJ
  template:
    metadata:
      creationTimestamp: null
      name: grafana-config
      namespace: monitoring
    type: Opaque

