apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-config
  namespace: monitoring
spec:
  encryptedData:
    grafana.ini: AgAB5POY/qGUqbialHnIcx9ui93fXDHbZtCVEZ+JhBBzlbmigWRQk3VwJrM/6B1asCUFy/OyGWKB0XdU29jtUM6FUzNMDBmOHJKyvkRd9NPGuQJx96/NZNF249jhTyjt+aJ9cdZh1V9fVdA0BZBS0JkXeKIRzljVtMH6pMy9NU4rHxeAAOffsIylEjDGMKKlkjjWtuyKM36lEhrAOALXJO4LkeZ/UYsjwVSx1QzzsZn773NfHTPbahp1OqYdvZs7w57oW/HLnbM1l3K5bE5Pfzu49V/O8OsPXhRAuOZC0JKbB4SBIbFceYiX1BZl+MoMY8iNc2Re6WfWl5Pbq7Uqa2+EgGHjLKft6R5D2RsNEF8IVc97v9arY6pydFlJu6DhPEh1vVxATDGvCDOgGyG/zt/p4m8+hO4WB/qFqdG5EdEz+O/IywZx9ghLx+uWzF1Py2vx6Cbcq1ZmICBvFypsJYGwNh4sqOsXdxaEtkosVE8a+NyCjZbt+qXy+K6NJCYwBZHIF4T9fMAcLhrlYsH3xh+ppx0JfbpfayhmO/j/2Gy2Dqt/69T5usYs0TdOS3h+vyb80YzZfOQ2j/NkAMg/TBEXz1g9GmUZ7ndYcI8lg5d+wD0V8O13MSy0pcu8e5s5uubZ+CbGqe687R1nFYj231C3WPA2Uw4E+WNvArXBrSB37zy7hUtvQtKLbPDzqn364B5rNJI0z5RK9UC/yGAGlL3tGVSPQ7Gsu0+uOLQ8TERuSyAv15S/3w+s8pMaeGb53JmMCPuJg2niNHdhihCa3pE8omuBJAzPPXvKvQXwnYo9OwQDX5plp07XcMApKPCF47Khz1AV8A1ZNp19ELnLixbpVVnRjt8lOoBilXoNHqOva3RG3CAPQSg0ZRFw+e1dQcjBxMD1js9xKQbm2jRvygbk/3FIWuo/QaT8pECYyv4Xk0I+cRPsQr7nXDWP3iD2aesDYwgf+B6e5MLVUgvUbxnuCe0SBk7G50P70RJDshlN7UKkK+hBbAGyBZxsoTJ13QjB/NAzQHxGMuFmZEVuoTxuYdxEFUGUPBoZwBRsEucdlQz46irbkaUaalPTmcke/GBo6pbLJIETPS4+35O6FxGItz/iLLugjGGJkgqVUsnKcape0OmABlEgyZZzncdxsQCRsjGX8F4AHAcv2K62CP/AcbCDzX/QWtqFOxTlvDTpM+arL3i90ohFHMwGqN/+jfhXS+AqhX6BUoznhFRuW8YQAVzl0HjRlrNa5hKZX0XJi0y4gMEzglFvkTDceoN5d0SdikrU0QS75ZGwzzBIWqAGqMGfV9BGda2spp33Gf6S6ZHBPiiCzpX8CeDKCebaUuMtfsHgjIi1SZEuw+95qtVChDQRcKT6gU4awx5DWnMtAPsUQ0NrUF7yFdhLrk3vG0NQ9I1fQRXYog==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-config
      namespace: monitoring
    type: Opaque

