apiVersion: kapp.k14s.io/v1alpha1
kind: Config
ownershipLabelRules:
  - path: [spec, template, metadata, labels]
    resourceMatchers:
      - apiVersionKindMatcher:
          { apiVersion: bitnami.com/v1alpha1, kind: SealedSecret }

rebaseRules:
  - path: [metadata, annotations, pv.kubernetes.io/bind-completed]
    type: copy
    sources: [new, existing]
    resourceMatchers: &pvcs
      - apiVersionKindMatcher:
          apiVersion: v1
          kind: PersistentVolumeClaim

  - path: [spec, volumeMode]
    type: copy
    sources: [new, existing]
    resourceMatchers: *pvcs
