#@data/values
---
git_url: https://github.com/voor/cluster-api-gitops
git_branch: origin/master
#! This is the file that gets populated from the management cluster postcreate secret, not this file.
workload_values: initial-values

# Secrets do not appear here.
github_client_id: ""
github_client_secret: ""
