#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workload-clusters
  namespace: kapp-controller
  annotations:
    kapp.k14s.io/disable-wait: "true"
spec:
  fetch:
  - git:
      url: https://github.com/voor/cluster-api-gitops
      ref: origin/master
      subPath: management-cluster/workload/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        #@ for secretRef in data.values.workload_secretRef:
        - secretRef:
            name: #@ secretRef
        #@ end 
  deploy:
  - kapp: {}