#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.not_op(overlay.subset({"apiVersion": "kapp.k14s.io/v1alpha1", "kind":"Config"})),expects="0+"
---
#@overlay/match missing_ok=True
metadata:
  namespace: workload-clusters

#@overlay/match by=overlay.subset({"kind":"AWSCluster"}),expects="0+"
---
spec:
  region: #@ data.values.aws.region
  sshKeyName: #@ data.values.aws.sshKeyName
  networkSpec:
    vpc:
      id: #@ data.values.aws.vpc.id
      #@overlay/remove
      cidrBlock:
    #@overlay/remove
    subnets:
  bastion:
    #@overlay/match missing_ok=True
    enabled: false
  #@overlay/match missing_ok=True
  controlPlaneLoadBalancer:
    #@overlay/match missing_ok=True
    scheme: internal

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        #@overlay/match missing_ok=True
        extraArgs:
          #@overlay/match missing_ok=True
          configure-cloud-routes: "false"