---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.10.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: 2.23.0
    app.kubernetes.io/managed-by: Helm
  name: dex
  namespace: sso
stringData:
  config.yaml: |
    issuer: https://login.sso.tanzu.world
    frontend:
      theme: tkg
    web:
      http: 0.0.0.0:5556
    expiry:
      signingKeys: "10m"
      idTokens: "5m"
    logger:
      level: "debug"
      format: "json"
    oauth2:
      skipApprovalScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: GITHUB_CLIENT_ID
        clientSecret: GITHUB_CLIENT_SECRET
        redirectURI: https://login.sso.tanzu.world/callback
        orgs: 
        - name: MY_GITHUB_ORG
        - name: MY_GITHUB_ORG-Teams
          teams:
          - MY_GITHUB_TEAM
    staticClients:
    - id: sonarqube-client
      secret: SONARQUBE_CLIENT_SECRET
      name: 'SonarQube'
      redirectURIs:
      - 'https://sonar.apps.tanzu.world/oauth2/callback'