#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.not_op(overlay.subset({"kind": "ServiceMonitor"})),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: external-dns