#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"external-dns"}})
---
spec:
  template:
    #@overlay/match missing_ok=True
    annotations:
      #@overlay/match missing_ok=True
      iam.amazonaws.com/role: #@ data.values.pod_role
    spec:
      containers:
      #@overlay/match by="name"
      - name: external-dns
        args:
        #@overlay/match by=overlay.subset("--aws-assume-role=arn:aws:iam::123455567:role/I-am-replaced-by-an-overlay-by-ytt")
        #@overlay/replace
        - #@ "--aws-assume-role={}".format(data.values.assumed_role)
        env:
        #@overlay/match by="name",when=1
        - name: CF_API_EMAIL
          value: #@ data.values.acme_email
        #@overlay/match by="name",when=1
        - name: AWS_DEFAULT_REGION
          value: #@ data.values.aws_region