#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@overlay/match by=overlay.all,expects="0+"
---
metadata:
  namespace: workload-clusters

#@overlay/match by=overlay.subset({"kind":"AWSCluster"})
---
spec:
  networkSpec:
    vpc:
      #@overlay/remove
      cidrBlock:
    #@overlay/remove
    subnets:
  bastion:
    #@overlay/match missing_ok=True
    enabled: false

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App

metadata:
  name: #@ "{}-postcreate".format(data.values.cluster_name)
  # namespace is going to be used as a default namespace during kapp deploy
  namespace: workload-clusters
  annotations:
    kapp.k14s.io/change-group: "gitops.tanzu.vmware.com/cni"
    kapp.k14s.io/change-rule: "upsert before upserting gitops.tanzu.vmware.com/kapp-controller"

spec:
  cluster:
    namespace: kube-system
    kubeconfigSecretRef:
      name:  #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value

  fetch:
  - inline:
        pathsFrom:
          - secretRef:
              name: #@ "{}-postcreate".format(data.values.cluster_name)
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App

metadata:
  name: #@ "{}-kapp-controller".format(data.values.cluster_name)
  # namespace is going to be used as a default namespace during kapp deploy
  namespace: workload-clusters
  annotations:
    kapp.k14s.io/change-group: "gitops.tanzu.vmware.com/kapp-controller"
    kapp.k14s.io/change-rule.1: "delete before deleting gitops.tanzu.vmware.com/cni"

spec:
  cluster:
    namespace: kube-system
    kubeconfigSecretRef:
      name:  #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value

  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.branch
      subPath: management-cluster/deploy/kapp-controller
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          clusteradmin-values.yaml: |
            #@ load("@ytt:data", "data")
            clusteradminrole: true
        pathsFrom:
          - secretRef:
              name: workload-clusters-secrets
  deploy:
  - kapp: {}

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App

metadata:
  name: #@ "{}-apps".format(data.values.cluster_name)
  # namespace is going to be used as a default namespace during kapp deploy
  namespace: workload-clusters
  annotations:
    kapp.k14s.io/change-group: "gitops.tanzu.vmware.com/remote-apps"
    kapp.k14s.io/change-rule.1: "delete before deleting gitops.tanzu.vmware.com/kapp-controller"
    kapp.k14s.io/change-rule.2: "upsert after upserting gitops.tanzu.vmware.com/kapp-controller"
    kapp.k14s.io/disable-wait: "true"

spec:
  cluster:
    namespace: kapp-controller
    kubeconfigSecretRef:
      name:  #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value

  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.branch
      subPath: workload/deploy
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}

---

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": { "name": "{}-postcreate".format(data.values.cluster_name) }})
---
#@overlay/replace via=lambda a,b: {"calico.yml": a["calicoYaml"]}
stringData: