apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgA49vJ8wajwjT+iGgYUcjMOmaVraIIq9gJeTyL45ehYgs+hCN4SiOV9DsDoawcC8WFCAz4fFi4fhqy8fhQjk7XUTxmpEBUx2zokSU0Bm4EKcRyj6RCi3tsY1Uv/Dh2fEzsX50+W1GekuGFhDYfMQArCPBQGtnsm0Y0o5t2Cgn++j1tmqK+mUC9wTczrWwrcDLwGLf0zH4M6+yuNBmFsmkdLlzHRC0mu+4u/hPjcBlJQfBf1pXcF68IaWsFkewuYthFaBcZ6/mIBPy8XdSWlmoKtMBHxBdrKdZYrhOINFWacrk7xYCkqgE3N1B5t8ih8NLGPzx0ch3SO/u5osQOGIHkjyPD8qJp5nOFPgSgrGqFXrWjoBC6fGZEh4SkqxJOJ/x6Yc7cp/tT93Gg2RSce8GEa89DQrSGzc4m8YahcBGZUAEMU22fuP6G+otc4HOtHlwrMJxKRyKDTtQ0yDWi1LcxiviUck85NZWNTv/yrMeI4u2PMJ6VWANlENOEb9j5zeRM9HGQZuulSg8ECJ22MD9zH6rb3vO05FlifSZuT6P8PQxUKR3mi9MD0C2uIoMdVFr8xQqdG/6/hc0A2hz83W1dnoUFXCowJusm9O1vyQF0JlFR1i1hVktjYmMxNzsa3yxu27uVxjsQmYzJZTkfGvqB5juXtca7+rem/BDbKvg8lgXfFMi92rda1EZBHaGupbKLIE7AW3h0TlgM/z08d0eMwgg==
    CF_API_TOKEN: AgAWQfa/U7DxAMFBpdJUOLuCviJydbOTDCUlF8gilvqzTnNqWbPHB43QMoEYSbUcGf364yl72qOM05LlxudfbV96WjcaW5GPkGoj1lu42a5OqAdNLYr7Vm3W1CaCqaa/G9MFcln7oGuNu/VX5WZlWIt9ai3uUCRhTADUO2Wue7/GqDVvdBfMa0/JWZ6zmSRwObhV7rsnjt/yPlYrZUhriFjTAwPS33BvlJ0RkQ+wum6LRo7NVfsxOb6hG1ofgZM1lLDH+boHHWbjueNouu94R0R412bgfYF2tyXS9vspcF/PB7SVKugMT1ho1WVneMPqm4dZiqXeUGfRq3/lXlbUpTxr+9nz8E1Qyr2TObDSljb4MSKzxQaNHaeHmSECfEoXopyG6bWrU+JUedV05GrdJhOcj9EduUNlJhnVma69JK1zyJEGh0gSVakTcK+eMA/VvH8aOSiAf6I2niWw6TodQ6xa9zjH0bFd6q6+ha6Ayjg8/cAYR/4X1s0VZU5pG0GCZDuU+fIf3zuHXh4NQ2YyxyMILvmdf5khmG2VNo7T6v6C6eUXJn9Gxq1ZE+33jtjlPH3r9ha7QaAIcLc12jv1W4N0HOJ9kWP3YWslWNhr34w7VuPjMQUayiPWjj6ifQFK4LtRzeaJpCzPtTRF9Q4BwAK+iSTvuPeKt+Mzh/IW57RVd6XNmmRDSe0uQCZF5nmFOnNfxTJ2Epae3YmvrdY2uVGM8dIKPbHG/LFqnFkQFH7peWzu0fxKWDUt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: external-dns
    type: Opaque
status: {}

