#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all,expects="0+"
---
metadata:
  namespace: workload-clusters

#@overlay/match by=overlay.subset({"kind":"AWSCluster"}),expects="0+"
---
spec:
  region: #@ data.values.aws.region
  sshKeyName: #@ data.values.aws.sshKeyName
  networkSpec:
    vpc:
      id: #@ data.values.aws.vpc.id
      #@overlay/remove
      cidrBlock:
    #@overlay/remove
    subnets:
  bastion:
    #@overlay/match missing_ok=True
    enabled: false
    