#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          #@overlay/match missing_ok=True
          oidc-client-id: #@ data.values.auth.client_id
          #@overlay/match missing_ok=True
          oidc-issuer-url: #@ data.values.auth.issuer_url
          #@overlay/match missing_ok=True
          oidc-username-claim: #@ data.values.auth.username_claim
          #@overlay/match missing_ok=True
          oidc-groups-claim: #@ data.values.auth.groups_claim