apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:

# cluster
- path: [spec, controlPlaneEndpoint]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: cluster.x-k8s.io/v1alpha3, kind: Cluster}

# aws cluster

- path: [spec, controlPlaneEndpoint]
  type: copy
  sources: [new, existing]
  resourceMatchers: &awscluster
  - apiVersionKindMatcher: {apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3, kind: AWSCluster}

- path: [metadata, labels, cluster.x-k8s.io/cluster-name]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, subnets, {allIndexes: true}, id]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, subnets, {allIndexes: true}, natGatewayId]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, subnets, {allIndexes: true}, routeTableId]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, subnets, {allIndexes: true}, isPublic]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, subnets, {allIndexes: true}, tags]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, vpc, id]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, vpc, internetGatewayId]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

- path: [spec, networkSpec, vpc, tags]
  type: copy
  sources: [new, existing]
  resourceMatchers: *awscluster

# control plane
- path: [metadata, labels, cluster.x-k8s.io/cluster-name]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: controlplane.cluster.x-k8s.io/v1alpha3, kind: KubeadmControlPlane}

# machine dep
- path: [metadata, labels, cluster.x-k8s.io/cluster-name]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: cluster.x-k8s.io/v1alpha3, kind: MachineDeployment}