apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: myfriend-md-1
  namespace: default
spec:
  template:
    spec:
      ami:
        id: ami-06a63cf3cf467b16f
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: m5.2xlarge
      rootVolume:
        size: 300
      sshKeyName: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: myfriend-md-1
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
            tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          name: '{{ ds.meta_data.local_hostname }}'
      useExperimentalRetryJoin: true
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: myfriend-md-1
  namespace: default
spec:
  clusterName: myfriend
  replicas: 6
  template:
    metadata:
      labels:
        node-pool: myfriend-worker-pool-1
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: myfriend-md-1
      clusterName: myfriend
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: myfriend-md-1
      version: v1.18.2+vmware.1
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: myfriend-md-1
  namespace: default
spec:
  clusterName: myfriend
  nodeStartupTimeout: 20m
  selector:
    matchLabels:
      node-pool: myfriend-worker-pool-1
  unhealthyConditions:
  - status: Unknown
    timeout: 5m
    type: Ready
  - status: "False"
    timeout: 5m
    type: Ready
