apiVersion: v1
data:
  autoTLS: "Enabled"
  ingress.class: contour.ingress.networking.knative.dev
  httpProtocol: "Redirected"
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving