---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.apps.tanzu.world'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: envoy
  namespace: contour-external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  tanzu.world: ""