image: vmware-docker-tkg.bintray.io/dex
imageTag: "v2.22.0_vmware.1"

telemetry: true

grpc: false

certs:
  web:
    create: false

livenessProbe:
  initialDelaySeconds: 2
  failureThreshold: 3
  timeoutSeconds: 2

readinessProbe:
  initialDelaySeconds: 8
  failureThreshold: 3
  timeoutSeconds: 1

config:
  issuer: http://dex.example.com:8080

  connectors: []
