apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-db-postgresql
  namespace: sonar
spec:
  encryptedData:
    postgresql-password: AgBr/WGIGT/3MrvEMHjvU/xWTMSKy3sBLXRD6U4H+fndB0QjyGbWeVmRsjGZh7O9iO02UoEs7Yytm5j8wlGHQCn6UHJptOxTsfP6QMYW7pC19gQrp5tT2SIBi2VjpHEYdHav/wGRX6anClPDQncEhp9Z0VjDSEHSEdZe/ExL++6LHO28MsiaipYn+ZmnYcgGEI08ngU4FfFIutayw88FpXvPXMLENincTgkHqM3dhiAKuNzyH15PTocWxw7/BQUwuSDpJoj7xSznWlpW0wWngQ1KAFFVfp9vEtCh1M3xFAiLO1QxKZd5fEw4Qc+ARmrO1HcbonJPmCJmyYg5S7lxTVqWVCQXhKEK/9qgiDYsmfKRh3sMPAHium5MQZz+nJgRdYlTN1eZ5u+j8oUVtDlAsDAsJzc4iOsa2gnoroGFOD61pB6CgCTclCVc4Gw/YFnI34bvXV/4XrkOW4PUghgQfOfF3bJEKf6XEJ+rWU4/kjxZVafYUeLxQMEz7fKaoC2J1a/39sjFjmIak/jnjLi1XdnT+0Wv8VcMC0cRTshUE2tGhqElsiQZxOz5QP6Xb3YqU02/wMikmYxVUbzsPc0CU0IB3nOJDI42sjnWTKaCAUQk1Ufs1C0Wo1ZFmcwUmWgd6MeCtXNoBSUvbCtUgCEpqNfxt7d2sFrefld8wxNsK5A4vrj3EqqJxNhHSsm2lBKcW4+MdIsUC5kDdBbEnFy86iE3sEEPOQ==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-db-postgresql
      namespace: sonar
    type: Opaque
status: {}

