apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcards
  namespace: apps
spec:
  delegations:
    - secretName: apps.tanzu.world
      targetNamespaces:
        - "*"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcards
  namespace: default
spec:
  delegations:
    - secretName: default.tanzu.world
      targetNamespaces:
        - "*"
